"""
terraform_export.py
===================

Turn the simulator's current state into Terraform (HCL) for the AWS provider.

Resources reference each other (``vpc_id = aws_vpc.prod.id``) instead of
hard-coding simulator IDs, so the output reads like hand-written IaC and
shows how console clicks map to code. The default VPC and each VPC's
auto-created main route table / default security group / default NACL are
skipped — Terraform does not create those either.
"""

from __future__ import annotations

import json
import re

import db
import rules


class _Names:
    """Stable, unique Terraform identifiers from resource names."""

    def __init__(self):
        self.used = set()
        self.by_id = {}

    def make(self, rid, name, fallback):
        base = re.sub(r"[^a-z0-9_]+", "_", (name or fallback).lower()).strip("_") or fallback
        if base[0].isdigit():
            base = f"r_{base}"
        ident, n = base, 2
        while ident in self.used:
            ident, n = f"{base}_{n}", n + 1
        self.used.add(ident)
        self.by_id[rid] = ident
        return ident


def _q(value):
    return json.dumps("" if value is None else str(value))


def _tags(name, extra=None):
    tags = {"Name": name} if name else {}
    tags.update(extra or {})
    if not tags:
        return ""
    body = "\n".join(f"    {k if re.fullmatch(r'[A-Za-z_][A-Za-z0-9_-]*', k) else _q(k)} = {_q(v)}"
                     for k, v in tags.items())
    return f"\n  tags = {{\n{body}\n  }}\n"


def _block(kind, ident, body):
    return f'resource "{kind}" "{ident}" {{\n{body.rstrip()}\n}}\n'


def _sg_rule_hcl(rule, direction, names):
    proto = rule["protocol"]
    lo = 0 if rule.get("from_port") is None else rule["from_port"]
    hi = 0 if rule.get("to_port") is None else rule["to_port"]
    if proto == "icmp" and rule.get("from_port") is None:
        lo, hi = -1, -1
    lines = [f"  {direction} {{", f"    protocol    = {_q(proto)}", f"    from_port   = {lo}", f"    to_port     = {hi}"]
    if rule.get("cidr"):
        lines.append(f"    cidr_blocks = [{_q(rule['cidr'])}]")
    elif rule.get("source_group") == "self":
        lines.append("    self        = true")
    elif rule.get("source_group"):
        ref = names.by_id.get(rule["source_group"])
        lines.append(f"    security_groups = [{f'aws_security_group.{ref}.id' if ref else _q(rule['source_group'])}]")
    if rule.get("description"):
        lines.append(f"    description = {_q(rule['description'])}")
    lines.append("  }")
    return "\n".join(lines)


def export(c):
    names = _Names()
    region = db.region(c)
    out = [
        "# Generated by Local AWS Simulator from the current environment.",
        "# Review before applying to a real account: `terraform init && terraform plan`.",
        "",
        'terraform {\n  required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n  }\n}\n',
        f'provider "aws" {{\n  region = {_q(region)}\n}}\n',
    ]
    vpcs = c.execute("SELECT * FROM vpcs WHERE is_default=0 ORDER BY id").fetchall()
    vpc_ids = {v["id"] for v in vpcs}
    for v in vpcs:
        ident = names.make(v["vpc_id"], v["name"], "vpc")
        names.by_id[("vpc", v["id"])] = ident
        out.append(_block("aws_vpc", ident,
                          f"  cidr_block           = {_q(v['cidr'])}\n"
                          f"  instance_tenancy     = {_q(v['tenancy'] or 'default')}\n"
                          f"  enable_dns_support   = {'true' if v['dns_support'] else 'false'}\n"
                          f"  enable_dns_hostnames = {'true' if v['dns_hostnames'] else 'false'}\n" + _tags(v["name"])))

    def vref(vpc_row_id):
        return f"aws_vpc.{names.by_id[('vpc', vpc_row_id)]}.id"

    subnets = [s for s in c.execute("SELECT * FROM subnets ORDER BY id") if s["vpc_id"] in vpc_ids]
    for s in subnets:
        ident = names.make(s["subnet_id"], s["name"], "subnet")
        names.by_id[("subnet", s["id"])] = ident
        out.append(_block("aws_subnet", ident,
                          f"  vpc_id                  = {vref(s['vpc_id'])}\n"
                          f"  cidr_block              = {_q(s['cidr'])}\n"
                          f"  availability_zone       = {_q(s['az'])}\n"
                          f"  map_public_ip_on_launch = {'true' if s['map_public_ip'] else 'false'}\n" + _tags(s["name"])))
    for g in c.execute("SELECT * FROM internet_gateways ORDER BY id"):
        if g["vpc_id"] not in vpc_ids:
            continue
        ident = names.make(g["igw_id"], g["name"], "igw")
        out.append(_block("aws_internet_gateway", ident, f"  vpc_id = {vref(g['vpc_id'])}\n" + _tags(g["name"])))
    eips = {e["allocation_id"]: e for e in c.execute("SELECT * FROM elastic_ips")}
    for n in c.execute("SELECT * FROM nat_gateways ORDER BY id"):
        if n["vpc_id"] not in vpc_ids:
            continue
        body = f"  subnet_id         = aws_subnet.{names.by_id[('subnet', n['subnet_id'])]}.id\n" \
               f"  connectivity_type = {_q(n['connectivity_type'])}\n"
        if n["allocation_id"] in eips:
            eident = names.make(n["allocation_id"], f"{n['name'] or 'nat'}_eip", "eip")
            out.append(_block("aws_eip", eident, '  domain = "vpc"\n'))
            body += f"  allocation_id     = aws_eip.{eident}.id\n"
        ident = names.make(n["nat_id"], n["name"], "nat")
        out.append(_block("aws_nat_gateway", ident, body + _tags(n["name"])))
    for e in eips.values():
        if e["allocation_id"] in names.by_id:
            continue
        names.make(e["allocation_id"], e["name"], "eip")
        out.append(_block("aws_eip", names.by_id[e["allocation_id"]], '  domain = "vpc"\n' + _tags(e["name"])))

    sgs = [g for g in c.execute("SELECT * FROM security_groups ORDER BY id") if g["vpc_id"] in vpc_ids and g["name"] != "default"]
    for g in sgs:
        names.make(g["group_id"], g["name"], "sg")
    for g in sgs:
        parts = [f"  name        = {_q(g['name'])}", f"  description = {_q(g['description'] or g['name'])}",
                 f"  vpc_id      = {vref(g['vpc_id'])}"]
        parts += [_sg_rule_hcl(r, "ingress", names) for r in rules.parse_sg_rules(g["inbound_json"])]
        parts += [_sg_rule_hcl(r, "egress", names) for r in rules.parse_sg_rules(g["outbound_json"])]
        out.append(_block("aws_security_group", names.by_id[g["group_id"]], "\n".join(parts) + "\n" + _tags(g["name"])))

    for rt in c.execute("SELECT * FROM route_tables WHERE main_table=0 ORDER BY id"):
        if rt["vpc_id"] not in vpc_ids:
            continue
        ident = names.make(rt["route_table_id"], rt["name"], "rt")
        body = f"  vpc_id = {vref(rt['vpc_id'])}\n"
        for r in rules.parse_routes(rt["routes_json"]):
            if r["target"] == "local":
                continue
            ref = names.by_id.get(r["target"])
            if r["target"].startswith("igw-"):
                tgt = f"gateway_id     = {'aws_internet_gateway.' + ref + '.id' if ref else _q(r['target'])}"
            elif r["target"].startswith("nat-"):
                tgt = f"nat_gateway_id = {'aws_nat_gateway.' + ref + '.id' if ref else _q(r['target'])}"
            else:
                tgt = f"gateway_id     = {_q(r['target'])}"
            body += f"\n  route {{\n    cidr_block     = {_q(r['destination'])}\n    {tgt}\n  }}\n"
        out.append(_block("aws_route_table", ident, body + _tags(rt["name"])))
        for s in c.execute("SELECT * FROM subnets WHERE route_table_id=?", (rt["id"],)):
            out.append(_block("aws_route_table_association", f"{names.by_id[('subnet', s['id'])]}_{ident}",
                              f"  subnet_id      = aws_subnet.{names.by_id[('subnet', s['id'])]}.id\n"
                              f"  route_table_id = aws_route_table.{ident}.id\n"))

    for lb in c.execute("SELECT * FROM load_balancers ORDER BY id"):
        ident = names.make(lb["lb_id"], lb["name"], "lb")
        subs = [s for s in subnets if s["name"] in json.loads(lb["subnets_json"] or "[]")
                or s["subnet_id"] in json.loads(lb["subnets_json"] or "[]")]
        sub_refs = ", ".join(f"aws_subnet.{names.by_id[('subnet', s['id'])]}.id" for s in subs)
        out.append(_block("aws_lb", ident,
                          f"  name               = {_q(lb['name'])}\n"
                          f"  load_balancer_type = {_q(lb['lb_type'])}\n"
                          f"  internal           = {'true' if lb['scheme'] == 'internal' else 'false'}\n"
                          f"  subnets            = [{sub_refs}]\n" + _tags(lb["name"])))

    for i in c.execute("SELECT * FROM ec2_instances WHERE state!='terminated' ORDER BY id"):
        ident = names.make(i["instance_id"], i["name"], "instance")
        cfg = json.loads(i["config_json"] or "{}")
        sub = c.execute("SELECT id, vpc_id FROM subnets WHERE subnet_id=?", (i["subnet"] or "",)).fetchone()
        body = f"  ami           = {_q(i['ami_id'])}  # {(cfg.get('ami') or {}).get('name', '')}\n" \
               f"  instance_type = {_q(i['instance_type'])}\n"
        if sub and sub["vpc_id"] in vpc_ids:
            body += f"  subnet_id     = aws_subnet.{names.by_id[('subnet', sub['id'])]}.id\n"
        sg_refs = [f"aws_security_group.{names.by_id[g]}.id" for g in (i["security_groups"] or "").split(",")
                   if g in names.by_id]
        if sg_refs:
            body += f"  vpc_security_group_ids = [{', '.join(sg_refs)}]\n"
        if i["key_name"]:
            body += f"  key_name      = {_q(i['key_name'])}\n"
        if cfg.get("termination_protection"):
            body += "  disable_api_termination = true\n"
        body += (f"\n  root_block_device {{\n    volume_size = {i['root_volume_gib'] or 8}\n"
                 f"    volume_type = {_q(i['root_volume_type'] or 'gp3')}\n"
                 f"    encrypted   = {'true' if i['encrypted'] else 'false'}\n  }}\n")
        body += "\n  metadata_options {\n    http_tokens = \"required\"\n  }\n"
        out.append(_block("aws_instance", ident, body + _tags(i["name"])))

    for b in c.execute("SELECT * FROM s3_buckets ORDER BY id"):
        ident = names.make(b["name"], b["name"], "bucket")
        out.append(_block("aws_s3_bucket", ident, f"  bucket = {_q(b['name'])}\n"))
        if b["versioning"]:
            out.append(_block("aws_s3_bucket_versioning", ident,
                              f"  bucket = aws_s3_bucket.{ident}.id\n  versioning_configuration {{\n    status = \"Enabled\"\n  }}\n"))
        if not b["public"]:
            out.append(_block("aws_s3_bucket_public_access_block", ident,
                              f"  bucket                  = aws_s3_bucket.{ident}.id\n"
                              "  block_public_acls       = true\n  block_public_policy     = true\n"
                              "  ignore_public_acls      = true\n  restrict_public_buckets = true\n"))

    for u in c.execute("SELECT * FROM iam_users ORDER BY id"):
        out.append(_block("aws_iam_user", names.make(u["arn"], u["name"], "user"), f"  name = {_q(u['name'])}\n"))
    for r in c.execute("SELECT * FROM iam_roles ORDER BY id"):
        ident = names.make(r["arn"], r["name"], "role")
        trust = r["trust_policy"] or json.dumps({"Version": "2012-10-17", "Statement": [
            {"Effect": "Allow", "Principal": {"Service": r["trusted_service"] or "ec2.amazonaws.com"},
             "Action": "sts:AssumeRole"}]})
        out.append(_block("aws_iam_role", ident, f"  name               = {_q(r['name'])}\n"
                          f"  assume_role_policy = jsonencode({_hcl_json(json.loads(trust))})\n"))
    for p in c.execute("SELECT * FROM iam_policies ORDER BY id"):
        ident = names.make(p["arn"], p["name"], "policy")
        try:
            doc = _hcl_json(json.loads(p["document"] or "{}"))
            policy = f"jsonencode({doc})"
        except ValueError:
            policy = _q(p["document"])
        out.append(_block("aws_iam_policy", ident, f"  name   = {_q(p['name'])}\n  policy = {policy}\n"))
    for a in c.execute("SELECT * FROM iam_policy_attachments ORDER BY id"):
        pref = names.by_id.get(a["policy_arn"])
        policy = f"aws_iam_policy.{pref}.arn" if pref else _q(a["policy_arn"])
        kind = "role" if a["principal_type"] == "role" else "user"
        pr = c.execute(f"SELECT arn FROM iam_{kind}s WHERE name=?", (a["principal_name"],)).fetchone()
        pident = names.by_id.get(pr["arn"]) if pr else None
        principal = f"aws_iam_{kind}.{pident}.name" if pident else _q(a["principal_name"])
        out.append(_block(f"aws_iam_{kind}_policy_attachment", f"{kind}_{a['id']}",
                          f"  {kind}       = {principal}\n  policy_arn = {policy}\n"))

    for f in c.execute("SELECT * FROM lambda_functions ORDER BY id"):
        ident = names.make(f["arn"], f["name"], "function")
        role = names.by_id.get(f["role"] or "")
        role_ref = f"aws_iam_role.{role}.arn" if role else _q(f["role"] or "arn:aws:iam::123456789012:role/CHANGE-ME")
        out.append(_block("aws_lambda_function", ident,
                          f"  function_name = {_q(f['name'])}\n  runtime       = {_q(f['runtime'])}\n"
                          f"  handler       = {_q(f['handler'])}\n  memory_size   = {f['memory_mb']}\n"
                          f"  timeout       = {f['timeout_s']}\n  role          = {role_ref}\n"
                          f"  filename      = \"{ident}.zip\"  # package the function code here\n"))
    for t in c.execute("SELECT * FROM dynamodb_tables ORDER BY id"):
        ident = names.make(t["arn"], t["name"], "table")
        body = f"  name         = {_q(t['name'])}\n  billing_mode = {_q(t['billing_mode'] or 'PAY_PER_REQUEST')}\n" \
               f"  hash_key     = {_q(t['partition_key'])}\n"
        if t["sort_key"]:
            body += f"  range_key    = {_q(t['sort_key'])}\n"
        if (t["billing_mode"] or "") == "PROVISIONED":
            body += "  read_capacity  = 5\n  write_capacity = 5\n"
        body += f"\n  attribute {{\n    name = {_q(t['partition_key'])}\n    type = {_q(t['partition_key_type'] or 'S')}\n  }}\n"
        if t["sort_key"]:
            body += f"\n  attribute {{\n    name = {_q(t['sort_key'])}\n    type = {_q(t['sort_key_type'] or 'S')}\n  }}\n"
        out.append(_block("aws_dynamodb_table", ident, body))
    secrets = c.execute("SELECT * FROM secrets ORDER BY id").fetchall()
    for s in secrets:
        ident = names.make(s["arn"], s["name"], "secret")
        out.append(_block("aws_secretsmanager_secret", ident,
                          f"  name        = {_q(s['name'])}\n  description = {_q(s['description'] or '')}\n"))
        out.append(_block("aws_secretsmanager_secret_version", ident,
                          f"  secret_id     = aws_secretsmanager_secret.{ident}.id\n"
                          f"  secret_string = var.{ident}_value  # never commit secret values\n"))
        out.insert(5, f'variable "{ident}_value" {{\n  type      = string\n  sensitive = true\n}}\n')
    return "\n".join(out)


def _hcl_json(value, indent=2):
    """Render JSON as an HCL object expression for jsonencode()."""
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [f"{pad}  {json.dumps(k)} = {_hcl_json(v, indent + 2)}" for k, v in value.items()]
        return "{\n" + "\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        return "[" + ", ".join(_hcl_json(v, indent) for v in value) + "]"
    return json.dumps(value)
